# ---------------------------------------------------------------------------------------------------------- #
# Título TFG: Testbed para la optimización del posicionamiento de servicios en el continuo Cloud-Fog-Edge    #
# Grado en Ingeniería de Tecnologías de Telecomunicación                                                     #
# Nombre y Apellidos Alumno: Antonio Aguilera González                                                       #   
# ---------------------------------------------------------------------------------------------------------- #

# Fichero de configuración .YAML para la creación de los servicios multimedia e iPerf3:
# ACLARACIÓN. Para la creación y ejecución de los containers, de manera simple, se emplea el comando "docker compose up"

version: "3.5"

# Docker Volumes (Para mantener los datos de manera persistente)
volumes:
    papermc_data:
        name: papermc_data

# Docker services
services:
    # Paper MC
    papermc:
        image: itzg/minecraft-server
        environment:
            EULA: "true"
            TYPE: PAPER
            VERSION: 1.20.4
            CONSOLE: "true"
            ONLINE_MODE: "false"

        container_name: papermc
        restart: always
        volumes:
            - papermc_data:/data
            
        ports:
            - "25565:25565"
    # iPerf3
    iperf3:
        image: networkstatic/iperf3
        container_name: iperf3
        command: ["-s"] # iPerf3 en modo servidor
        restart: always
        ports:
            - "5201:5201/udp"
            - "5201:5201/tcp"